title: I think it's a site made of boredom
author: May
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is an awesome description of my site. We're talking about nothing, really.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme : minima
